### ISSUE TITLE
release plan about Super Sparse 3D object Detection?

### ISSUE THREAD

**Issue by rXYZkit** [tusen-ai/SST#104]
Thank you for your good work!

Do you have the plan to release the corresponding code of _Super Sparse 3D object Detection_?

**Comment by Abyssaledge** [comment]
Yes, we will release the code. The data pipeline of FSD++ is quite different from the released FSD, so it takes effort to make it compatible with this repo. Our submission is undergoing a revision and we are also developing some new work. So be patient and we plan to release the code before June.

**Comment by Abyssaledge** [comment]
Yes, we will release the code. The data pipeline of FSD++ is quite different from the released FSD, so it takes effort to make it compatible with this repo. Our submission is undergoing a revision and we are also developing some new work. So be patient and we plan to release the code before June.
