### ISSUE TITLE
will CTRL_FSD_TTA be open source?

### ISSUE THREAD

**Issue by 20210726** [tusen-ai/SST#105]
I'm interested in CTRL_FSD_TTA（https://waymo.com/open/challenges/entry/?challenge=DETECTION_3D&challengeId=DETECTION_3D&emailId=1cb154ab-1558&timestamp=1678678070312349），will it be open source?

**Comment by Abyssaledge** [comment]
Yes we will release the code but it may take a couple of months since the paper is not public.

**Comment by lcc815** [comment]
any updated plan to release the code?

**Comment by Abyssaledge** [comment]
Thanks very much for your attention, please stay tuned patiently. If we are lucky with the submission, code release will be given the highest priority.

**Comment by JuiceLemonLemon** [comment]
Hello, I'm aslo interested in CTRL. So I would like to know when will this code be released？

**Comment by Abyssaledge** [comment]
@20210726  @lcc815 @JuiceLemonLemon Hi, CTRL is released now.

**Comment by JuiceLemonLemon** [comment]
> @20210726 @lcc815 @JuiceLemonLemon Hi, CTRL is released now.

ok, thank you very much.

**Comment by JuiceLemonLemon** [comment]
@Abyssaledge 
Hello,
Thank you for your sharing, and could you please tell me the password to get the resource in below link.

https://share.weiyun.com/1r6VsFfJ
