### ISSUE TITLE
Request for pretrained weights for SST model on WOD dataset

### ISSUE THREAD

**Issue by jb892** [tusen-ai/SST#106]
Hi there,

I'm currently working on a project that requires the use of the SST model. I noticed that the repository doesn't provide pretrained weights for this model.

Would it be possible to provide pretrained weights for the SST model on WOD dataset? This would be very helpful and save me a lot of time.

Thank you!

**Comment by Abyssaledge** [comment]
Give me your email, I will send it to you as a private link since WOD does not allow distributing the pretrained weights.

**Comment by jb892** [comment]
Great! Please send to this address: jack-jubo@hotmail.com. Thanks!
