### ISSUE TITLE
About 2stage Argoverse  configuration file

### ISSUE THREAD

**Issue by seonhoon1002** [tusen-ai/SST#109]
Hello, I have a great time traveling your codes.
But I'm not able to find the "2stage(= FSD, not SingleStageFSD)" configuration file for Argoverse(or maybe I missed something). So, If you don't mind, can I ask you to upload the "2stage" configuration file for the Argoverse dataset?

**Comment by Abyssaledge** [comment]
Thanks for your use.
We only use the single-stage model for Argoverse 2 Dataset. It contains 30 categories, the two-stage model will introduce too many class-wise hyperparameters and reduce the generalization.
