### ISSUE TITLE
fsd_sst_encoder_pretrain on nuScenes 

### ISSUE THREAD

**Issue by JuiceLemonLemon** [tusen-ai/SST#110]
Hello,
Thank you for your sharing, I have a question about fsd pretrain,
Could I use the fast pretrain config (e.g., fsd_sst_encoder_pretrain) for a once-for-all warmup on nuScenes dataset?

**Comment by Abyssaledge** [comment]
FSD does not officially support nuScenes for now. We will update a new version of FSD to support nuScenes in a month.

**Comment by JuiceLemonLemon** [comment]
ok, thank you very much.

**Comment by JuiceLemonLemon** [comment]
> FSD does not officially support nuScenes for now. We will update a new version of FSD to support nuScenes in a month.

@Abyssaledge 
Hello, sorry to bother you.
But I want to know when will you release the FSD for nuScenes?
