### ISSUE TITLE
wiil TCO module be open sourced?

### ISSUE THREAD

**Issue by slkxnw** [tusen-ai/SST#112]
TCO improves the performance of CTRL, i'm interested in it. but it seems that tool/CTRL doesn't have C++ code, i wonder if it will be open sourced, or it's wroten by python?

**Comment by Abyssaledge** [comment]
TCO is isolated from the detection part in this repo, and Yiming Mao is the developer of TCO. You could contact him using the email in our paper for more information.

**Comment by slkxnw** [comment]
thank you very much! i will contact Mr. Mao later

**Comment by Joeless** [comment]
In TCO, the core operator is accelerated by CUDA. I will open source in late July. @slkxnw

**Comment by slkxnw** [comment]
> In TCO, the core operator is accelerated by CUDA. I will open source in late July. @slkxnw

Thank you!

**Comment by Furchtlos001** [comment]
@Joeless @Abyssaledge  @slkxnw   I would like to know if TCO is open sourced.

**Comment by darnellMJ** [comment]
> In TCO, the core operator is accelerated by CUDA. I will open source in late July. @slkxnw

@Joeless @slkxnw Hello，if TCO is open sourced？I would like to communication about TCO. And I could not contact Mr. Mao using the email in paper.
