### ISSUE TITLE
spec-file.txt - link not found error [UPDATE]

### ISSUE THREAD

**Issue by ragini9m** [tusen-ai/SST#114]
I got error for the following links and I have added the updated links-

1. HTTP 404 NOT FOUND for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-1.0.1-py3.6_cuda8.0.61_cudnn7.1.2_2.tar.bz2>  
```
https://conda.anaconda.org/pytorch/noarch/torchvision-cpu-0.2.2-py_3.tar.bz2
```

**Comment by Abyssaledge** [comment]
It seems a PyTorch issue. It would be better to look for a solution in PyTorch repo or PyTorch Forums.
