### ISSUE TITLE
CTRL resource share password

### ISSUE THREAD

**Issue by JuiceLemonLemon** [tusen-ai/SST#116]
Hello,
Thank you for your sharing, and could you please tell me the password to get the resource in below link.

https://share.weiyun.com/1r6VsFfJ

**Comment by Abyssaledge** [comment]
Please follow the instruction and send me an email. I cannot distribute the password here. @JuiceLemonLemon

**Comment by JuiceLemonLemon** [comment]
ok, thank you very much, I have send the email.
