### ISSUE TITLE
A question about result of Runtime Evaluation in paper

### ISSUE THREAD

**Issue by slkxnw** [tusen-ai/SST#122]
hello, I read your paper and was impressed by the result of Runtime Evaluation, which shows that the Refine Stage takes only 6s. I wonder if TCO module works in evaluation? Cause it's quite a large optimization problem when there are many objects in a 20s sequence

**Comment by Abyssaledge** [comment]
No, TCO is excluded when conducting the runtime evaluation. In fact, TCO is slower than the refinement.

**Comment by slkxnw** [comment]
could you please give me some information about the tco runtime. i write a demo of tco, and it takes a lot of time, about 30s/obj(300 frame)

**Comment by Abyssaledge** [comment]
You could contact Yiming Mao, the developer of TCO, for more information.
