### ISSUE TITLE
look forward to the modified ImmortalTracker

### ISSUE THREAD

**Issue by 20210726** [tusen-ai/SST#124]
look forward to the modified ImmortalTracker，thanks！

**Comment by dof-pikes** [comment]
+1

**Comment by Abyssaledge** [comment]
Thanks for your attention, we release the tailored ImmortalTracker here: https://github.com/Abyssaledge/ImmortalTracker-for-CTRL
@dof-pikes @20210726

**Comment by dof-pikes** [comment]
@Abyssaledge  Thanks！！
