### ISSUE TITLE
How to get the detection_results.bin?

### ISSUE THREAD

**Issue by xiaocongcsu** [tusen-ai/SST#129]
Hi~Thanks for your great job
And I wondering how to get the waymo detection_results.bin?

> We recommand you to use CenterPoint(two-frame model for tracking) detection results for reproducing our results. Please follow https://github.com/tianweiy/CenterPoint or email its author for CenterPoint detection results.

**Comment by Abyssaledge** [comment]
This is the instruction of the official ImmortalTracker repo. I do not have the CenterPoint detection results. I could provide you the result files of the FSD series detectors if you need.

**Comment by xiaocongcsu** [comment]
> 

I‘ll appreciate it if you can send me the FSD series detectors results, my email is "xiaocongcsu@163.com".
Thanks again~

**Comment by Abyssaledge** [comment]
OK, but I am currently inaccessible to our server, I will send it to you next week.
Feel free to remind me if I forget.
@xiaocongcsu
