### ISSUE TITLE
how to generate detection results for CTRL

### ISSUE THREAD

**Issue by yrt1993** [tusen-ai/SST#131]
hi, I wonder how to generate detection results in the training step 2

https://github.com/tusen-ai/SST/blob/main/docs/CTRL_instructions.md#step-2-use-immortaltracker-to-generate-tracking-results-in-training-split-bin-file-format

**Comment by Abyssaledge** [comment]
Using any detectors and inference on the Waymo dataset, then you can get the detection results. You could use the FSD in this repo if you need it.

**Comment by Abyssaledge** [comment]
Please reopen this issue if you need further discussion.

**Comment by rockywind** [comment]
训练CTRL一定要有跟踪标签吗？
数据集可以是单帧的吗？

**Comment by rockywind** [comment]
@Abyssaledge @yrt1993 
 您好，请问一下，FSDV2跑waymo数据集，如何存成bin格式的。
![image](https://github.com/tusen-ai/SST/assets/14838781/3fe4530e-0629-4f73-9e7c-e6e69ca82965)
