### ISSUE TITLE
 KeyError: 'FSDV2SparseUNet is not in the models registry'

### ISSUE THREAD

**Issue by yrt1993** [tusen-ai/SST#136]
when I want to train fsdv2 using fsdv2_waymo_2x_bb01_ms.py, the error occurs.

**Comment by Abyssaledge** [comment]
It seems you have got the results in another issue. Is it solved now?

**Comment by yrt1993** [comment]
no. I got the results using fsdv2_waymo_2x.py

**Comment by Abyssaledge** [comment]
Why do you use `fsdv2_waymo_2x_bb01_ms.py` instead of the released one? This is the developing config. Although they actually share the same model structure, I rename some modules, so you got this error.
