### ISSUE TITLE
Evaluation of FSDv2 on Waymo dataset

### ISSUE THREAD

**Issue by ArseniuML** [tusen-ai/SST#139]
I am trying to perform testing FSDv2 on Waymo dataset:

```
DIR=fsdv2
WORK=work_dirs/pretrained
CONFIG=fsdv2_waymo_2x
python tools/test.py configs/$DIR/$CONFIG.py ./$WORK/$CONFIG/latest.pth --eval waymo
```

There is an error:
`
/bin/sh: 1: mmdet3d/core/evaluation/waymo_utils/compute_detection_metrics_main: not found`

folder work_dirs/pretrained/fsdv2_waymo_2x contains files downloaded from Google Drive link.

What can cause this error?

**Comment by Abyssaledge** [comment]
Please follow https://github.com/tusen-ai/SST/blob/main/docs/overall_instructions.md#fast-waymo-evaluation to install waymo evaluation tool.
