### ISSUE TITLE
How to generate the "waymo_infos_train.pkl" in the extract_poses.py

### ISSUE THREAD

**Issue by rockywind** [tusen-ai/SST#148]
Hi, thank you for sharing the great work.
I don't know how to generate the pkl in the below when I run the ctrl in waymo dataset.
![image](https://github.com/tusen-ai/SST/assets/14838781/c1ddb7ae-cb41-4826-bc5e-527803d0d16e)

**Comment by Abyssaledge** [comment]
They are generated by MMDet3D script: `tools/create_data.py` or `tools/create_data.sh`, which converts Waymo raw data to KITTI format.

**Comment by rockywind** [comment]
Thanks a lot!
