### ISSUE TITLE
How to remove the false detection?

### ISSUE THREAD

**Issue by rockywind** [tusen-ai/SST#149]
Hi, 
Why the nms not remove the false detection?
![image](https://github.com/tusen-ai/SST/assets/14838781/656cb3a0-758a-4070-ba95-d12c1b7b8fb4)
This is my config.
![image](https://github.com/tusen-ai/SST/assets/14838781/925c2285-7993-4a37-80d4-d962c6411b95)

**Comment by atlantins** [comment]
How you get the visulization photo like the first one ？

**Comment by eagle-chase** [comment]
The default algorithm used should be 3diou_ NMS, I think other NMS methods can be used for large targets or the IoU threshold can be lowered

**Comment by Abyssaledge** [comment]
Because their IoU is less than 0.25.

**Comment by rockywind** [comment]
@Abyssaledge 
I think it need a nms between multi-class.
The white is the truck and the pink is the bus.
Their IOU is very large.
