### ISSUE TITLE
error in performance of ctrl

### ISSUE THREAD

**Issue by yrt1993** [tusen-ai/SST#151]
hi，I tried to reproduce the results of ctrl，and I got the following results:

OBJECT_TYPE_TYPE_VEHICLE_LEVEL_1: [mAP 0.874662] [mAPH 0.867681]
OBJECT_TYPE_TYPE_VEHICLE_LEVEL_2: [mAP 0.810487] [mAPH 0.803212]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_1: [mAP 0.885251] [mAPH 0.835387]
OBJECT_TYPE_TYPE_PEDESTRIAN_LEVEL_2: [mAP 0.824893] [mAPH 0.774855]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_1: [mAP 0.817697] [mAPH 0.810792]
OBJECT_TYPE_TYPE_CYCLIST_LEVEL_2: [mAP 0.797658] [mAPH 0.790865]

It don't use the optional step2 and 5 to extend and remove empty. It seems that the results of vehicle and pedestrian is OK, but the 
metric of cyclist is much lower that those in the paper. 

Can you give me some advice and your train log if possible

![loss](https://github.com/tusen-ai/SST/assets/39512783/6af1d602-be75-447b-9ca3-efdb000505f6)

**Comment by Abyssaledge** [comment]
Sorry, I cannot provide you with the training log, which is not kept. Which **base** bin file of the cyclist did you use?
