### ISSUE TITLE
What's the definition of the coordinate when the argoverse dataset transform to kitti format?

### ISSUE THREAD

**Issue by rockywind** [tusen-ai/SST#154]
Hi, thank you for sharing the great work!
I am confuse the definition of  coordinate and the yaw transform.
The xyz is the 3D box center on kitti lidar coordinate or not?
Why need the yaw transform?
![image](https://github.com/tusen-ai/SST/assets/14838781/2e422206-7f32-40d2-8003-9eb4620fb013)

**Comment by Abyssaledge** [comment]
Here we convert the box format to [LiDARInstance3DBboxes](https://github.com/tusen-ai/SST/blob/main/mmdet3d/core/bbox/structures/lidar_box3d.py#L15).
It is hard to explain the details. But all transformations serve the same purpose to suit LiDARInstance3DBoxes.

**Comment by rockywind** [comment]
thanks a lot.
