### ISSUE TITLE
How to visulize a sequence in a pcd or photo?

### ISSUE THREAD

**Issue by atlantins** [tusen-ai/SST#157]
不知道你们之前是否有可视化连续帧的vis tool，如论文所说，一旦检测就不会丢失，不知道如何可视化一段连续帧的检测结果来证明这个观点，而不是只有一张某一帧结果的检测图片

**Comment by Abyssaledge** [comment]
你可以自行把单帧的结果做成连续的gif，我们论文中是用定量数据体现的，没有可视化工具。

**Comment by atlantins** [comment]
Thanks！
