### ISSUE TITLE
Can you provide the config or pth for the ctrl's 9 frame base detetor 

### ISSUE THREAD

**Issue by atlantins** [tusen-ai/SST#164]

**Comment by Abyssaledge** [comment]
Sorry for the late reply, I am quite busy lately.
In the dev branch, the config is https://github.com/tusen-ai/SST/blob/dev/configs/fsd/fsd_waymoD1_1x_futuresweeps_framedrop.py 
Before using the config, you should use the following script to generate the 9-frame pickle file. Please modify the input path in the script to the original pickle you use.
https://github.com/tusen-ai/SST/blob/dev/tools/generate_futuresweepspkl.py

**Comment by Abyssaledge** [comment]
@atlantins
