### ISSUE TITLE
how to generate kitti style train.txt file

### ISSUE THREAD

**Issue by SakuraRiven** [tusen-ai/SST#168]
Hi, we try to use ```python tools/create_data.py``` but found that it needs txt files such as  ```ImageSets/train.txt``` in ```kitti_format``` dir.

How could we generate these txt files so that we can reproduce the CTRL work?

Thanks for your kind help : )

**Comment by SakuraRiven** [comment]
Our method: collect the ```idxs``` from ```idx2contextname.pkl``` and assign idxs to train/val/test in terms of their corresponding context_names

**Comment by Abyssaledge** [comment]
Sorry for the late reply. We have been quite busy lately. Your solution seems nice, did it work? I can upload these files if you need.

**Comment by SakuraRiven** [comment]
@Abyssaledge  It works well and we have reproduced the pipeline successfully : )
