### ISSUE TITLE
Question about Argoverse validation dataset order 

### ISSUE THREAD

**Issue by seonhoon1002** [tusen-ai/SST#177]
Hello, I have a question regarding the order of the Argoverse validation dataset

When I visualize the Argo dataset processed by your code, the order seems shuffled(other datasets are not shuffled)

Below is a visualization result of Argoverse(of course, I check the shuffle args in dataset loader)
![argoverse](https://github.com/tusen-ai/SST/assets/41002216/5ab1f08d-a83f-40a5-b478-c7688f96fabc)

Below is a visualization result of Waymo 
![waymo](https://github.com/tusen-ai/SST/assets/41002216/fe2b2bce-67b9-4285-93f3-cdec104340f1)

In your case, Is Argoverse Dataset shuffled?
So it is a natural phenomenon when we get the argoverse dataset by argo2 library?

**Comment by Abyssaledge** [comment]
I didn't shuffle it on purpose. I believe you can get the ordered results by sorting the resulted pkl file.

**Comment by seonhoon1002** [comment]
In Waymo and Nuscense case, their order is correct, yes, so that's why we can use "sweep".

So I have a question about this: does your data processing process involve sorting the order in Waymo or Nuscense case?
