### ISSUE TITLE
How to generate idx2timestamp.pkl and idx2contextname.pkl?

### ISSUE THREAD

**Issue by yvanwy** [tusen-ai/SST#179]
In the "overall_instructions.md", It states that we need copy tools/idx2timestamp.pkl and tools/idx2contextname.pkl to ./data/waymo/kitti_format/.
I can find these 2 files, but I don't know how to generate these 2 files?

**Comment by Abyssaledge** [comment]
All the information is contained in waymo_infos_train/val/test.pkl. You could easily extract the two files from the pkl files.

**Comment by yvanwy** [comment]
thanks
