### ISSUE TITLE
GPU and graphics memory issues

### ISSUE THREAD

**Issue by yinheyanxian** [tusen-ai/SST#186]
Thank you for your wonderful work. I would like to know if I can train and test the performance of your algorithm on the argoverse2 dataset on a 3090Ti GPU  with 24GB of graphics memory?

**Comment by Abyssaledge** [comment]
Sorry for the late reply.  Yes, you can use 3090. All my experiments are conducted with 3090 GPU.

**Comment by ameizi3** [comment]
Sorry to bother you, are you training on a single 3090 GPU or multiple 3090 GPUs?
