### ISSUE TITLE
Using test-time augmentations while metrics evaluating

### ISSUE THREAD

**Issue by ArseniuML** [tusen-ai/SST#209]
Do I can use test-time augmentations while metrics evaluating (for example in Argo2)? I They must be applied to GT annotations before evaluation, but it seems that gt annotations is read from 'sensor/val_anno.feather' and no validation pipeline is applied to them...

**Comment by Abyssaledge** [comment]
I do not understand what you mean by "they must be applied to GT annotations before evaluation". TTA does not rely on annotations.

**Comment by ArseniuML** [comment]
If I use GlobalRotScaleTrans with non-zero parameters in test pipeline, I have to apply the same transformations to GT boxes during evaluation.

**Comment by ArseniuML** [comment]
What I want is not a TTA.
