### ISSUE TITLE
how to realize the "Visualization of a SST detection sequence by AB3DMOT tracking"

### ISSUE THREAD

**Issue by sjtuljw520** [tusen-ai/SST#51]
In reamde, there is a gif showing the "Visualization of a SST detection sequence by AB3DMOT tracking", anyone know how to do it?

**Comment by Abyssaledge** [comment]
Could you be more specific and let us know which part you do not know how to deal with?

**Comment by sjtuljw520** [comment]
Thanks for replying, can you sharing the code to do the visualization as below ?
<img width="380" alt="emobile_2022-08-10_13-44-57" src="https://user-images.githubusercontent.com/8221858/183824959-11d06ed3-90a9-4fbd-aa86-d5acd93039b0.png">

**Comment by Abyssaledge** [comment]
We use the visualization tools in [SimpleTrack](https://github.com/TuSimple/SimpleTrack#demo-and-api-example). Hope it helps.

**Comment by sjtuljw520** [comment]
OK, thank you very much! @Abyssaledge
