### ISSUE TITLE
performance of centerpoint and PC-RCNN in your paper

### ISSUE THREAD

**Issue by seonhoon1002** [tusen-ai/SST#56]
Hello, I have question about performance in FSD paper in table 1

Bellow is your table which guessed tested on Waymo  V1.2.0 validation
![image](https://user-images.githubusercontent.com/41002216/185784209-b9f13e54-5c4b-41ca-a815-64c3cfc0f523.png)

And this is the table in Centerpoint
![image](https://user-images.githubusercontent.com/41002216/185784254-e360d07d-239c-46ac-aa27-f24975a8f19d.png)

And this is two version of PV-RCNN paper
![image](https://user-images.githubusercontent.com/41002216/185784316-9d3ff526-3044-41a6-a333-10d48c3efbb1.png)

I think CenterPoint was measured from Waymo V1.0

Could I ask how did you know what version of Waymo for applying the Centerpoint

**Comment by Abyssaledge** [comment]
CenterPoint uses WOD >= 1.2. Note that Level 1 and Level 2 are different. Performance of Level 1 only takes GT containing more than 5 points into account.

**Comment by seonhoon1002** [comment]
So if you're right, did centerpoint enter the wrong performacne about "PV-RCNN". 
Because PVRCNN performances in LV2 in centerpoint are **"vehicle: 65.4AP/64.8APH, pedestrian: 53.9AP/46.7APH"**
but performance in LV2 in original paper are **vehicle: 68.98AP/68.41APH, pedestrian: 66.04AP/57.61APH**

**Comment by Abyssaledge** [comment]
Sorry for late reply. Both of them are right. The reported performance of PVRCNN in many papers are different because of different re-implementation and different version of dataset. I recommend to refer to the updated performance in PVRCNN paper.

**Comment by seonhoon1002** [comment]
OK I see, Thank you
