### ISSUE TITLE
How much GPU resources are required?

### ISSUE THREAD

**Issue by medlen** [tusen-ai/SST#58]
How long does it take to train on waymo dataset? and how much GPU resources are required? Four 3090 or V100?  Can NVIDIA TITAN TRX 24G train this model ?

**Comment by Abyssaledge** [comment]
Thanks for using. The single-frame Waymo model can be trained on 2080Ti with batchsize=1.  For the full training dataset and 2x schedule (24 epochs), it takes around 3 days in 8 2080Ti GPUs.
