### ISSUE TITLE
How do you visualize?

### ISSUE THREAD

**Issue by cjfghddl0206** [tusen-ai/SST#59]
I used the kitti dataset to draw checkpoints and results, but I couldn't find any code to visualize it. What code can you visualize within your code?

**Comment by Abyssaledge** [comment]
I do not release the visualization code, which is very messy and just for developing purpose, abandoned long time ago.
There are no technical difficulties to do visualization, only a matter of programming. 
You could randomly choosing a query, and save the attention weights as well as the corresponding voxel coordinates. Then, use the coordinates to find the corresponding points. Finally, paint the weights on the points.
