### ISSUE TITLE
Training logs of SST+CenterHead

### ISSUE THREAD

**Issue by woxihuanjiangguo** [tusen-ai/SST#60]
Hello. Thank you for your great work! I would appreciate it if you can provide the training logs of the CenterHead version of your model.

**Comment by Abyssaledge** [comment]
Sorry for late reply, here is the training log
[sst_center_full24e.log](https://github.com/tusen-ai/SST/files/9573123/sst_center_full24e.log)
Let me know if you have any further questions.

**Comment by woxihuanjiangguo** [comment]
Thank you!!
