### ISSUE TITLE
About Lidar RCNN and pedestrain

### ISSUE THREAD

**Issue by SSY-1276** [tusen-ai/SST#63]
作者您好！
我看您使用Lidar RCNN作为二阶段网络，所以想向您请教一下关于Lidar RCNN的问题。我用Centerpoint+Lidar RCNN，pedestrain类别相比于Centerpoint一阶段一直出现掉点情况，听说您使pedestrain类别涨点很多，请问您对Lidar RCNN做了哪些调整呢？谢谢

**Comment by Abyssaledge** [comment]
您好，我直接使用了lidarrcnn作者的代码，分别训练了vehicle类别和pedestrian类别，没有做任何改动．

**Comment by SSY-1276** [comment]
好的，谢谢发自我的手机-------- 原始邮件 --------发件人： Lue Fan ***@***.***>日期： 2022年9月21日周三 下午1:39收件人： tusen-ai/SST ***@***.***>抄送： SSY-1276 ***@***.***>, Author ***@***.***>主    题： Re: [tusen-ai/SST] About Lidar RCNN and pedestrain (Issue #63)

您好，我直接使用了lidarrcnn作者的代码，分别训练了vehicle类别和pedestrian类别，没有做任何改动．
