### ISSUE TITLE
The question about voxelize

### ISSUE THREAD

**Issue by Fengshihao1** [tusen-ai/SST#64]
作者，您好！
非常感谢您的工作！
我对体素化的过程有一点困惑。在您的SST工作中，对输入的雷达点会首先进行voxelize：
在mmdet3d/models/detectors/dynamic_voxelnet.py中的：
def voxelize(self, points):
"""Apply dynamic voxelization to points.
Args:
points (list[torch.Tensor]): Points of each sample.
Returns：
tuple[torch.Tensor]: Concatenated points and coordinates.
"""
这里输入的points是列表的形式，请问列表的长度是batchsize的大小吗？

**Comment by Abyssaledge** [comment]
是的．
