### ISSUE TITLE
How to fix point offset direction reverse in segmentation_head?

### ISSUE THREAD

**Issue by wutheringcoo** [tusen-ai/SST#69]
I use points in bbox to predict offset form center of bbox, loss function is smothl1, most method is from segmentation_head, but i found offset direction is often reverse, How to fix this problem?
vis is below:
![1111](https://user-images.githubusercontent.com/43715279/192737988-c7212daa-2097-4156-b261-ce727324eaf7.png)

**Comment by wutheringcoo** [comment]
I have check offset targets visualization, gt vis is below
ps: predicted offset in my model is trained in my dataset, i use your idea in my instance_head, picture above is trained 28epoch,   train dataset: 25000frames
![222](https://user-images.githubusercontent.com/43715279/192743388-fcb686b6-7762-418b-afd6-3875fcfa4d09.png)

**Comment by Abyssaledge** [comment]
Do you change the model structure before segmentation_head? If you do, which part do you modify?

**Comment by wutheringcoo** [comment]
backbone use my own model structure, instance_head predicts offset from your segmentation_head
