### ISSUE TITLE
When I change the seg_voxel_size to train custom dataset, the voxel2point neck gives the following error,what does it mean?

### ISSUE THREAD

**Issue by XLMore** [tusen-ai/SST#70]
![image](https://user-images.githubusercontent.com/46312249/192931322-81de5d47-ebd0-4879-a11a-fcfc3edd7bf0.png)

**Comment by Abyssaledge** [comment]
It means you may not correctly mask those points out of point_cloud_range.

**Comment by XLMore** [comment]
> It means you may not correctly mask those points out of point_cloud_range.
I set the voxel_size and pc_range as follows:
seg_voxel_size = (0.16, 0.16, 0.22)
point_cloud_range = [-80, -32, -2.2, 80, 32, 4.4]

**Comment by Abyssaledge** [comment]
How about the point_cloud_range in your data_cfg? The one in data_cfg is used  in PointsRangeFilter.

**Comment by XLMore** [comment]
> PointsRangeFilter
point_cloud_range in data_cfg is the same as in waymo-fsd.py which is [-74.88, -74.88, -1.999, 74.88, 74.88, 3.999]，and the point_cloud_range in fsd_waymoD1_1x is also differenr from that in data_cfg, How can I change it accordingly?

**Comment by XLMore** [comment]
> > PointsRangeFilter
> > point_cloud_range in data_cfg is the same as in waymo-fsd.py which is [-74.88, -74.88, -1.999, 74.88, 74.88, 3.999]，and the point_cloud_range in fsd_waymoD1_1x is also differenr from that in data_cfg, How can I change it accordingly?

point_cloud_range in data_cfg must be a sub_set of point_cloud_range outside,I'll give it a try

**Comment by XLMore** [comment]
what is the small margin in z axis of point_cloud_range of data_cfg used for?

**Comment by Abyssaledge** [comment]
You are supposed to change to point_cloud_range in data config to fit your dataset. The small margin makes the voxelization more safe.

**Comment by XLMore** [comment]
I changed the point_cloud_range according to your advice and get the train loop run. But after some iterations,the loss curve looks very strange
![image](https://user-images.githubusercontent.com/46312249/193013252-5d947e16-295c-4753-baf7-77fe1777c375.png)
![image](https://user-images.githubusercontent.com/46312249/193013376-16e70fa4-a875-42b5-b6f4-9c0983be7ba9.png)
Is it normal because it's still in the early epoches?

**Comment by XLMore** [comment]
I think the sparse_shape in VoteSegmentor backnone is also affected by the point cloud range, but I have no clue, Do you have any advice?

**Comment by Abyssaledge** [comment]
Note that we use `EnableFSDDetectionHookIter` hook, which means FSD model will first train segmentor for couple of iterations for warmup and then enable following detection part. So the early epochs may not effective.
