### ISSUE TITLE
Extractly how much gpu memory is used when running sst training?

### ISSUE THREAD

**Issue by cjfghddl0206** [tusen-ai/SST#72]
I was trying to make and run a config file for the kitti dataset with only one RTX 3090, but it came out of memory and I need an accurate gpu memory number.

**Comment by Abyssaledge** [comment]
[sst_waymoD5_1x_3class_8heads_v2.log](https://github.com/tusen-ai/SST/files/9689623/sst_waymoD5_1x_3class_8heads_v2.log)
Here is the training log, which contains all the training stats. Hope it helps.
