### ISSUE TITLE
question about fast run

### ISSUE THREAD

**Issue by pansanity666** [tusen-ai/SST#75]
Hi, 
   The waymo dataset is too large. Is it possible to run the code without downloading the waymo dataset, e.g., a lightweight demo? (I only want to know the implementation details about the code so that I can better use it, e.g., input and output shape of each function.)
Best,

**Comment by Abyssaledge** [comment]
Yes, you could download a single waymo data file [here](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_3_1_individual_files;tab=objects?pli=1&prefix=&forceOnObjectsSortingFiltering=false).
After that we could provide a pretrianed model.

**Comment by pansanity666** [comment]
> Yes, you could download a single waymo data file [here](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_3_1_individual_files;tab=objects?pli=1&prefix=&forceOnObjectsSortingFiltering=false). After that we could provide a pretrianed model.

Thank you for you reply! But the 'download' button on your provided website is gray and can not be clicked. Dont know specifically how to download this file. Is there download link from google drive etc?
Best,

**Comment by Abyssaledge** [comment]
You could refer to the individual files in this [page](https://waymo.com/open/download/)

**Comment by pansanity666** [comment]
> You could refer to the individual files in this [page](https://waymo.com/open/download/)

Thanks. The individual file can be downloaded after registration. 
Next, should I process the individual file following the same procedure as in mmdetection3d?

**Comment by Abyssaledge** [comment]
I recommend to follow their documents but use the code in this repo to process the data, due to official MMDet3D update the coordinates system.

**Comment by pansanity666** [comment]
> I recommend to follow their documents but use the code in this repo to process the data, due to official MMDet3D update the coordinates system.

Thanks. The mini-dataset has been ready by little modification on the data converter script. Well, where should I get the pre-trained checkpoint then? (If I have not miss something in README.md.)
Best,

**Comment by Abyssaledge** [comment]
Just give me your email and I will send you a private link.

**Comment by pansanity666** [comment]
***@***.***, thanks!
-----Original Messages-----
From:"Lue Fan" ***@***.***>
Sent Time:2022-10-10 07:51:30 (Monday)
To: tusen-ai/SST ***@***.***>
Cc: "Xiao Pan" ***@***.***>, Author ***@***.***>
Subject: Re: [tusen-ai/SST] question about fast run (Issue #75)






Just give me your email and I will send you a private link.

**Comment by Abyssaledge** [comment]
Could you show me the email at this page? The email address will be blocked if you reply via email.

**Comment by pansanity666** [comment]
> Could you show me the email at this page? The email address will be blocked if you reply via email.
xiaopan@zju.edu.cn, Thank!

**Comment by Abyssaledge** [comment]
I have sent you the link.

**Comment by pansanity666** [comment]
> I have sent you the link

Appreciated!
