### ISSUE TITLE
Do you use TTA when use config fsd_waymoD1_1x_submission.py?

### ISSUE THREAD

**Issue by poodarchu** [tusen-ai/SST#79]

**Comment by poodarchu** [comment]
@Abyssaledge 
https://github.com/tusen-ai/SST/blob/main/configs/_base_/datasets/waymo-fsd.py#L129

**Comment by Abyssaledge** [comment]
It is dummy pipeline, not enabled.

**Comment by Abyssaledge** [comment]
It is dummy pipeline, not enabled.
