### ISSUE TITLE
About measuring model compelexities

### ISSUE THREAD

**Issue by seonhoon1002** [tusen-ai/SST#80]
Hello, Can I ask you how to measure the model complexities of #param and Memory in the SST paper?

**Comment by Abyssaledge** [comment]
The number of parameters is calculated in a handcrafted way. As for memory, we report the memory reported in the log at the begining of second epoch.

**Comment by seonhoon1002** [comment]
So in the memory report, did it measure in inference time?

**Comment by Abyssaledge** [comment]
No, we report the memory footprint in training time.

**Comment by seonhoon1002** [comment]
Ok, I understand.
Thanks!
