### ISSUE TITLE
Can you upload a FSD plain configuration file?

### ISSUE THREAD

**Issue by seonhoon1002** [tusen-ai/SST#81]
Hi, thanks for your great work!
I want to see FSD_plain real visualization results in my envrionment. 
So can you upload a FSD_plain configuration file?

**Comment by Abyssaledge** [comment]
Sorry, FSD_plain is implemented in our internal codebase. It is currently not supported in this codebase.
However, it could be simply implemented by replacing the input group centers with voxel centers in the SparseClusterHeadV2.

**Comment by seonhoon1002** [comment]
Ok, I see.
Thanks~
