### ISSUE TITLE
Can the FSD model run without GPU (cuda)?

### ISSUE THREAD

**Issue by sjtuljw520** [tusen-ai/SST#83]
Hi, I want to train and test the FSD model only with CPU due to limited GPU resources. Is that possible?

**Comment by Abyssaledge** [comment]
Sorry, you cannot run FSD on CPU since a couple of operators like GroupCorrection (in TorchEx) are only supported on GPU.

**Comment by sjtuljw520** [comment]
OK, thank you very much for replying. @Abyssaledge
