### ISSUE TITLE
No module named 'dynamic_point_pool_ext'

### ISSUE THREAD

**Issue by baiwuchang** [tusen-ai/SST#84]
After I install SST and try to run, it gives the error :
ModuleNotFoundError: No module named 'dynamic_point_pool_ext'

I move 'import dynamic_point_pool_ext'  inside the class of DynamicPointPoolFunction to avoid running program with this line of code, then I can run the code of SST.

When i run FSD, it still gives the error that  No module named 'dynamic_point_pool_ext'. I find that 'dynamic_point_pool_ext' is not in setup.py.  So what should I do?

**Comment by happynear** [comment]
Before using this repo, please install [TorchEx](https://github.com/Abyssaledge/TorchEx), [SpConv2](https://github.com/traveller59/spconv) (SpConv 1.x is not supported) and [torch_scatter](https://github.com/rusty1s/pytorch_scatter).
