### ISSUE TITLE
About FSD spconv configuration(fsd_waymoD1_1x.py)

### ISSUE THREAD

**Issue by seonhoon1002** [tusen-ai/SST#87]
Hello,
Can I ask "fsd_waymoD1_1x.py" configuration?

In your paper, "†: Adopting longer schedule (12 epochs) and decreasing the number
of pasted instances in the data augmentation to prevent the model from overfitting Cyclist class." for spconv which shows best performance in your paper

So is this configuration applied to "fsd_waymoD1_1x.py" in this repository?

**Comment by Abyssaledge** [comment]
Yes
