### ISSUE TITLE
How to process Argoverse 2 Dataset？

### ISSUE THREAD

**Issue by foolhard** [tusen-ai/SST#98]
Hi, 

Thanks for your great job and sharing the code. 

I see your scripts to process Argoverse2 dataset to Kitti. Could you give some guide on how to use them?
 
`./tools/argo`

**Comment by Abyssaledge** [comment]
Detailed instructions will be updated here very soon: https://github.com/tusen-ai/SST/blob/main/instructions.md

**Comment by foolhard** [comment]
Thanks for feedback.
