### ISSUE TITLE
How can I train this pretrained model argo_segmentation_pretrain.pth from scratch?

### ISSUE THREAD

**Issue by jiangxuan2023** [tusen-ai/SST#99]

**Comment by Abyssaledge** [comment]
Sorry for missing this part, we will update the segmentation config very soon.

**Comment by jiangxuan2023** [comment]
First of all, thank you for your reply; and, I have another question to ask, when will the code of FSD++ be open source?

**Comment by Abyssaledge** [comment]
We have no clear schedule for releasing the code of FSD++ since the manuscript is still in submission.
However, if the community is interested in the work, we could release the code in near future.

**Comment by Abyssaledge** [comment]
And the argo segmentation config is updated, FYI. @jiangxuan2023
